export const styles = {
  container: { background: '#020617', color: '#f8fafc', minHeight: '100vh', padding: '0 40px 40px', fontFamily: '"Inter", sans-serif' },
  header: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', padding: '30px 0', borderBottom: '1px solid #1e293b', marginBottom: '30px' },
  brand: { display: 'flex', alignItems: 'center', gap: '15px' },
  logoIcon: { background: '#6366f1', padding: '8px', borderRadius: '8px' },
  title: { fontSize: '1.25rem', fontWeight: '800', margin: 0 },
  subTitle: { color: '#6366f1', fontWeight: '400' },
  tagline: { fontSize: '0.75rem', color: '#64748b', margin: 0 },
  controlGroup: { display: 'flex', gap: '12px' },
  inputWrapper: { display: 'flex', alignItems: 'center', background: '#0f172a', border: '1px solid #1e293b', padding: '6px 12px', borderRadius: '8px' },
  ghostInput: { background: 'none', border: 'none', color: '#fff', width: '50px', outline: 'none', fontWeight: 'bold' },
  inputLabel: { fontSize: '0.7rem', color: '#475569', textTransform: 'uppercase' },
  mainGrid: { display: 'grid', gridTemplateColumns: '60% 38%', gap: '2%', alignItems: 'start' },
  showcasePanel: { background: '#0f172a', borderRadius: '24px', border: '1px solid #1e293b', padding: '32px' },
  scrollArea: { background: '#020617', borderRadius: '20px', padding: '25px', border: '1px solid #1e293b', maxHeight: '480px', overflowY: 'auto' },
  panelHeader: { display: 'flex', justifyContent: 'space-between', marginBottom: '25px' },
  panelTitle: { fontSize: '1.1rem', fontWeight: '600', margin: 0, display: 'flex', alignItems: 'center' },
  specGrid: { display: 'grid', gridTemplateColumns: 'repeat(2, 1fr)', gap: '20px' },
  specCard: { background: '#0f172a', padding: '20px', borderRadius: '16px', border: '1px solid #1e293b' },
  specLabel: { fontSize: '0.65rem', color: '#64748b', textTransform: 'uppercase', marginBottom: '8px', display: 'block' },
  specValue: { fontSize: '1rem', fontWeight: '700', marginBottom: '4px', display: 'flex', alignItems: 'center', gap: '10px' },
  specSub: { fontSize: '0.75rem', color: '#475569' },
  resultBanner: { marginTop: '32px', display: 'flex', justifyContent: 'space-between', background: '#020617', padding: '20px', borderRadius: '20px', border: '1px solid #1e293b' },
  winnerBadge: { display: 'flex', gap: '16px', alignItems: 'center' },
  statusBadge: (isClick) => ({ padding: '6px 12px', borderRadius: '6px', fontSize: '0.7rem', fontWeight: '800', background: isClick ? 'rgba(16, 185, 129, 0.1)' : 'rgba(239, 68, 68, 0.1)', color: isClick ? '#10b981' : '#ef4444', border: `1px solid ${isClick ? '#10b981' : '#ef4444'}` }),
  sidebarPanel: { display: 'flex', flexDirection: 'column', gap: '30px' },
  sidebarSection: { background: '#0f172a', borderRadius: '24px', border: '1px solid #1e293b', padding: '25px' },
  chartBox: { height: '320px', background: '#020617', borderRadius: '16px', padding: '15px' },
  primaryBtn: { background: '#6366f1', color: '#fff', border: 'none', padding: '10px 20px', borderRadius: '8px', fontWeight: '600', cursor: 'pointer' },
  secondaryBtn: { background: 'transparent', color: '#cbd5e1', border: '1px solid #334155', padding: '10px 20px', borderRadius: '8px', fontWeight: '600', cursor: 'pointer' },
  ctaBtn: { background: '#10b981', color: '#fff', border: 'none', padding: '10px 20px', borderRadius: '8px', fontWeight: '600', cursor: 'pointer' }
};